### ISSUE TITLE
Demonstrate how to debug in vscode by including .vscode/launch.json

### ISSUE THREAD

**Issue by jaybo** [hawkeye64/electron-quasar-file-explorer#145]
There's a dearth of good examples of how to debug Quasar electron apps in vscode, and I'm stuck.  It would be great if you could add a working launch.json to this project.  Presumably something similar to:

    https://github.com/bromix/vue-electron-app/blob/master/.vscode/launch.json

with appropriate substitutions.

**Comment by hawkeye64** [comment]
I only ever use vscode debugging for backend. Sorry, I wouldn't know about electron. I just use old-style `degugger` and dev tools.
