### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by dipaliso** [hawkeye64/electron-quasar-file-explorer#19]
I am new to Electron and Vue. Just tried to run `yarn dev` all I see is a blank screen. Does it have anything to do with the `Electron Security Warning (Disabled webSecurity)`?

![image](https://user-images.githubusercontent.com/1003257/62419360-f3530080-b69b-11e9-9ddf-138d1ad45ea6.png)

**Comment by hawkeye64** [comment]
You probably got a version of Electron that's changed. I should have locked the version. I'll take a look at it this weekend.

**Comment by dipaliso** [comment]
Prolly something to do with the env? But didn't find `.env` file.

`mainWindow.loadURL(process.env.APP_URL)`

**Comment by dipaliso** [comment]
Never mind. Setting env `APP_URL=http://127.0.0.1:8080` works!
