### ISSUE TITLE
Modified date time in list view is displayed incorrectly

### ISSUE THREAD

**Issue by Noboxulus** [hawkeye64/electron-quasar-file-explorer#2]
It is caused by the highlighted line in src/pages/contents.vue:

![image](https://user-images.githubusercontent.com/19311003/55708186-dcffa580-5a17-11e9-9ebd-dd6b0edf5c34.png)

changing the line to the below fixes it for me:
`      return moment.utc(node.data.stat.mtime).format('YYYY-DD-MM h:mm:ss a')`

for those who want to display local time and not UTC time (using the locale of your machine/device):
`      return moment.utc(node.data.stat.mtime).local().format('YYYY-DD-MM h:mm:ss a')`

**Comment by hawkeye64** [comment]
Thanks for finding this issue and the fix.
I'll be taking a look at this on the weekend.

**Comment by hawkeye64** [comment]
Fixed in latest. And, thanks again.
