### ISSUE TITLE
can't load and file if i clicked shortcut

### ISSUE THREAD

**Issue by KiDeokKim** [hawkeye64/electron-quasar-file-explorer#248]
hi, i'm tried to create new project and showing file explorer in windows. and i'm beginner.
if i click C drive and d drive, it is changed and show files and folder.
but if i click shortcut button(like pictures, music etc..), elctron paused and showing error
- Paused before potential out-of-memory crash

maybe it caused from vue.runtime.esm.js in node_modules/vue/dist
error caused line is 4627 in proxy function.

how can i fixed this error? and if i clicked shortcut button, setSelectedFolder function is called twice. is it correct?
p.s. i think pressed shortcut button is occur infinity loop..

added - i can't load child path from C drive or D drive. why i can't load my child path from drive folder?
and if i run your project, it cause vue warn 
- Invalid prop: type check failed for prop "absolutePath". Expected String with value "null", got Null
found in ---> <Breadcrumbs> at src/components/breadcrumbs.vue
warn : vue.runtime.esm.js 620 line...

**Comment by hawkeye64** [comment]
@KiDeokKim Likely from dependency changes. When I get some time I can look into it, but right now I am slammed with work.

**Comment by KiDeokKim** [comment]
okay, so i tell you how to setting my project.
- create quasar project and copy-paste your package.json and install dependency from yarn (i'm just using yarn. not using npm)
- get your util folder and components folder, i will using router view So create new vue file and copy-modify your mainLayout.vue for router-view
- modify electron-main.dev.js and electron-main.js, modify .eslintrc.js

that's it. i will check your function flow and why caused out-of-memory and stopped electron.

current state
- cannot show C: , D: child node(folders) if i click under arrow(breadcrumb? right?)
- but if i click C or D , it is showing first child folder&file contents.
- common error : if i double click second folder from C or D & shortcut folder(pictures etc..), it is stopped and cause out-of-memory

**Comment by KiDeokKim** [comment]
okay, i found why my project is not working.
probably quasar in node_modules is different my project and your project.
so delete node_modules/quasar in my project and copy node_modules/quasar in your project
and that's work. but i want why doesn't work added quasar from yarn.

when you have a time, please check node_module/quasar.
this is my node_modules/quasar : https://drive.google.com/file/d/1TFSTxjA3mi_QNjaLnxNQ-u11zRPXaFyp/view?usp=sharing

and I think there is a problem with the q-tree. It didn't work normally in the lazyload part.

**Comment by KiDeokKim** [comment]
sorry it is another question.
your file browser can get files, so i want get file information like <input type="file"/>.

we can get filepath and name etc from node.nodekey and node.label.
and if i get fileinfo from <input type="file"/>, we can get fileinfo and return jsontype (ex : File {name: "blabla", path: "blabla~")
i want get jsontype like input type file.. how can i get fileinfo like input type file?

**Comment by hawkeye64** [comment]
You can use the fs node module (FileSystem) to "stat" your selected file or stat them all in a folder and append to current data (will be slower)

**Comment by KiDeokKim** [comment]
i'm solved. using filesystem and call readFileSync from nodekey and create Blob object and File. 
thanks to your comments and please check changed dependency to quasar.
