### ISSUE TITLE
when i start program, show warning in breadcrumbs

### ISSUE THREAD

**Issue by KiDeokKim** [hawkeye64/electron-quasar-file-explorer#255]
if i start quasar application, console show this error.

Invalid prop: type check failed for prop "absolutePath". Expected String with value "null", got Null 

found in

---> <Breadcrumbs> at src/components/breadcrumbs.vue

how to fix it?

**Comment by hawkeye64** [comment]
This repo is not compatible with Quasar v2/Vue v3
Use this one instead: https://github.com/hawkeye64/electron-quasar-file-explorer-v2
